name: conecapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#android
#version: 1.0.0+11
#ios
version: 1.0.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.5.0
  carousel_slider: ^2.2.1
  share: ^0.6.4+3
  flutter_rating_bar: ^3.2.0+1
  flutter_html: ^1.0.0-pre.1
  package_info: ^0.4.0+16
  chips_choice: ^2.0.1
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.7+4
  characters: ^1.0.0
  flutter_svg: ^0.18.0
  flutter_slidable: ^0.5.5
  fluttertoast: ^7.0.2
  file_picker: ^1.13.3
  google_maps_flutter: ^0.5.30
  geocoder: ^0.2.1
  tiengviet: ^0.4.1
  geolocator: ^6.0.0+4
  video_player: ^0.10.12+3
  html_editor: ^1.0.1
  flutter_datetime_picker: ^1.4.0
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0
  flutter_zalo_login: 0.1.3
  badges: ^1.1.3
  sign_in_with_apple: ^2.5.4
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  onesignal_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/conec_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Male
      fonts:
        - asset: assets/fonts/Male.ttf
    - family: Female
      fonts:
        - asset: assets/fonts/Female.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
